
@startuml

' CLI task to remain the only active task
' rest of tasks deinited in a determined state

' Perhaps its a safe reset, init procedure will need to be safe to
start
:Disable all drivers;
:Close RTOS tasks;
:Notify of reset;
:System reset;
stop